services:
  - type: web
    name: flask-evaluation-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import db; db.create_all()"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: evaluation_db
          property: connectionString
